spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf8
  jpa:
    show-sql: true
    database: mysql
#  jackson:
#    default-property-inclusion: non_null

#server:
#  context-path: /sell
